### ISSUE TITLE
Port alternate addresses from couchbase-cli

### ISSUE THREAD

**Issue by avsej** [couchbaselabs/cbdinocluster#23]
It would be great if cbdinocluster had a command that sets alternate addresses, and even better if I can specified it in the cluster definition YAML file.

Here is the documentation of couchbase-cli how it could be done there:
https://github.com/couchbase/couchbase-cli/blob/master/docs/modules/cli/pages/cbcli/couchbase-cli-setting-alternate-address.adoc

This is implementation in python:
https://github.com/couchbase/couchbase-cli/blob/a75b06d91e81cea14ebeb4b83aa39ba9240d1b29/cbmgr.py#L5073

It would also require to configure the networking in docker to actually listen on those addresses.

**Comment by brett19** [comment]
I'm going to close this issue since alternate addresses was addressed 'for free' in an environment which more accurately reflects a true alternate addresses environment through the K8S support added recently.
