### ISSUE TITLE
Display fully-qualified image name in `images search` output

### ISSUE THREAD

**Issue by dnault** [couchbaselabs/cbdinocluster#31]
It would be nice if we could copy and paste a fully-qualified image name from `images search` into a `docker run` command.

Current output (some result lines removed for brevity):
```
> cbdinocluster images search 7.2
Images:
  7.2.3 [Source: dockerhub]
  7.2.5-7524 [Source: ghcr]
```

Desired output, something like:

```
> cbdinocluster images search 7.2
Images:
  7.2.3 [Source: docker.io/couchbase/server:7.2.3]
  7.2.5-7524 [Source: ghcr.io/cb-vanilla/server:7.2.5-7524]
```

**Comment by brett19** [comment]
What's the use-case for explicitly running a container image outside of dinocluster?

**Comment by brett19** [comment]
Fair enough, in case it wasn't obvious, there are examples of cluster definitions in the examples/ folder in the repo:
https://github.com/couchbaselabs/cbdinocluster/tree/master/examples/cluster-defs

The simple-3.yaml file is essentially what you get from the `simple` short-string.
