### ISSUE TITLE
`buckets add` command is not accepting ramQuota value

### ISSUE THREAD

**Issue by Aaliya7516** [couchbaselabs/cbdinocluster#5]

**Comment by Aaliya7516** [comment]
Hello team, please let us know if there is any command flag, through which we can provide Ram Quota while creating a bucket.

**Comment by brett19** [comment]
Completed in https://github.com/couchbaselabs/cbdinocluster/commit/2a616288e09c82f62e80731ec4f0a17a82bb9c6b
