### ISSUE TITLE
Command to get Certs is needed

### ISSUE THREAD

**Issue by Aaliya7516** [couchbaselabs/cbdinocluster#6]
Please let us know if there is any command to get the certs form capella.

**Comment by brett19** [comment]
This is not currently supported, but the certificate is the same for all Capella clusters, and the SDKs should have this certificate built in already.

**Comment by Aaliya7516** [comment]
Hello @brett19, this is not an urgent requirement as we are running cbDino commands against [cloud environment](https://cloud.couchbase.com/) and cloud env creates a bundle of certs. But in future we need to run cbDino against [sandbox](https://xyz.sandbox.nonprod-project-avengers.com)/[dev](https://dev.nonprod-project-avengers.com/)/[stage](https://stage.nonprod-project-avengers.com/) environment (we generally prefer sandbox for testing) we will need a command to generate a cert because these environment don't provide a bundle of certifications, etc.

**Comment by brett19** [comment]
Completed as part of the referenced pull request.

**Comment by Aaliya7516** [comment]
Thanks Brett
